services:
    web:
        build: .
        container_name: llm_chat_web
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        env_file:
            - .env
        volumes:
            - .:/app
        ports:
            - '8001:8000'
        restart: unless-stopped
