"""

Revision ID: c616424fda8c
Revises: 874f88d33a9f
Create Date: 2025-05-06 08:50:59.542938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c616424fda8c'
down_revision: Union[str, None] = '874f88d33a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_keyword_site', 'hotdeal_keyword_sites', ['keyword_id', 'site_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_keyword_site', 'hotdeal_keyword_sites', type_='unique')
    # ### end Alembic commands ###
